sudo: required

language: crystal

before_install:
  - sudo apt-get update 
  - sudo apt-get install -y liblapack-dev liblapack-doc-man liblapack-doc liblapack-pic liblapack3 liblapack-test liblapack3gf liblapacke liblapacke-dev libblas-dev libblas-doc liblapacke-dev liblapack-doc
  
