sudo: required

language: crystal

addons: 
  apt:
    packages: 
      - gfortran
      - libblas3gf
      - liblapack3gf      
      - liblapack-dev
      - liblapack-pic 
      - liblapack3 
      - liblapack-test 
      - liblapack3gf 
      - liblapacke 
      - liblapacke-dev 
      - libblas-dev
