sudo: required

language: crystal

before_install:
  - sudo apt-get update 
  - sudo apt-get install -yqq liblapack-dev liblapack-pic liblapack3 liblapack-test liblapack3gf liblapacke liblapacke-dev libblas-dev
