sudo: required

language: crystal

services:
  - docker

before_install:
  - docker build https://github.com/mverzilli/crystalla.git -t crystalla

script:
  - docker run crystalla /bin/sh -c "crystal spec"
